const CompsEvents = Object.freeze({
  COMPS_LIST: "COMPS_EVENTS_COMPS_LIST",
  COMPS_LIST_ERROR: "COMPS_EVENTS_COMPS_LIST_ERROR",
  COMP_INFO: "COMPS_EVENTS_COMP_INFO",
  COMP_INFO_ERROR: "COMPS_EVENTS_COMP_INFO_ERROR",
  COMP_GAMES: "COMPS_EVENTS_COMP_GAMES",
  COMP_GAMES_ERROR: "COMPS_EVENTS_COMP_GAMES_ERROR",

  REGISTER_SUCCESS: "COMPS_EVENTS_REGISTER_SUCCESS",
  REGISTER_ERROR: "COMPS_EVENTS_REGISTER_ERROR",

  COMP_ENTER: "COMPS_EVENTS_COMP_ENTER"
});

export default CompsEvents;
