const CompsEvents = Object.freeze({
  COMPS_LIST: "COMPS_EVENTS_COMPS_LIST",
  COMPS_LIST_ERROR: "COMPS_EVENTS_COMPS_LIST_ERROR",
  COMP_INFO: "COMPS_EVENTS_COMP_INFO",
  COMP_INFO_ERROR: "COMPS_EVENTS_COMP_INFO_ERROR",

  REGISTER_SUCCESS: "COMPS_EVENTS_REGISTER_SUCCESS",
  REGISTER_ERROR: "COMPS_EVENTS_REGISTER_ERROR"
});

export default CompsEvents;
