const GamesEvents = Object.freeze({
  START: "GAMES_EVENTS_START",
  STATE: "GAMES_EVENTS_STATE",
  MOVE: "GAMES_EVENTS_MOVE",
  END: "GAMES_EVENTS_END",
  CONNECTION_OPENED: "GAMES_EVENTS_CONNECTION_OPENED",
  CONNECTION_CLOSED: "GAMES_EVENTS_CONNECTION_CLOSED",
  CONNECTION_ERROR: "GAMES_EVENTS_CONNECTION_ERROR",
  NEW_STATE: "GAMES_EVENTS_NEW_STATE"
});

export default GamesEvents;
