const GamesEvents = Object.freeze({
  GAMES_LIST: "GAMES_EVENTS_GAMES_LIST",
  GAMES_LIST_ERROR: "GAMES_EVENTS_GAMES_LIST_ERROR",
  GAME_INFO: "GAMES_EVENTS_GAME_INFO",
  GAME_INFO_ERROR: "GAMES_EVENTS_GAME_INFO_ERROR",

  REGISTER_SUCCESS: "GAMES_EVENTS_REGISTER_SUCCESS",
  REGISTER_ERROR: "GAMES_EVENTS_REGISTER_ERROR",

  CONNECTION_OPENED: "GAMES_EVENTS_CONNECTION_OPENED",
  CONNECTION_CLOSED: "GAMES_EVENTS_CONNECTION_CLOSED",
  CONNECTION_ERROR: "GAMES_EVENTS_CONNECTION_ERROR",

  INFO: "GAMES_EVENTS_INFO",
  HISTORY: "GAMES_EVENTS_HISTORY",
  START: "GAMES_EVENTS_START",
  STATE: "GAMES_EVENTS_STATE",
  MOVE: "GAMES_EVENTS_MOVE",
  REQUEST_MOVE: "GAMES_EVENTS_REQUEST_MOVE",
  END: "GAMES_EVENTS_END",

  NEW_STATE: "GAMES_EVENTS_NEW_STATE"
});

export default GamesEvents;
